### ISSUE TITLE
[Request] Add 'Operator Presets' to export settings

### ISSUE THREAD

**Issue by alfandango** [mrtripie/Blender-Batch-Export#1]
Great add-on, would love to see the addition of the Operator Pre-sets dropbown that is available in blender export window.  This would allow for more custom settings being used (and saved) at export

**Comment by mrtripie** [comment]
Thanks!
I've implemented it on the newest release. The presets are the same ones from the File > Export windows you mentioned, on the types that have a preset option.

**Comment by mrtripie** [comment]
I've went ahead and added a few other improvements to a new release now that I've looked at this addon's code again.

**Comment by alfandango** [comment]
> I've went ahead and added a few other improvements to a new release now that I've looked at this addon's code again.

This looks great!  Having an issue with 'object by parents' export though:
![image](https://user-images.githubusercontent.com/70297661/147286533-17fa2711-601b-4576-8421-6154b5ad706e.png)

**Comment by mrtripie** [comment]
> > I've went ahead and added a few other improvements to a new release now that I've looked at this addon's code again.
> 
> This looks great! Having an issue with 'object by parents' export though: ![image](https://user-images.githubusercontent.com/70297661/147286533-17fa2711-601b-4576-8421-6154b5ad706e.png)

Alright, that should be fixed now.
